# Generated by Django 2.0.7 on 2019-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcg',
            name='anode_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gcg',
            name='snode_num',
            field=models.IntegerField(default=0),
        ),
    ]
