# Generated by Django 2.0.7 on 2019-01-04 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPassCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='controlopengroup',
            name='og_custom_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
