# Generated by Django 2.0.7 on 2019-01-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0002_auto_20190108_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
