# Generated by Django 2.0.7 on 2019-01-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0002_auto_20190107_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlgroup',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_custom_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_lm_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_mode',
            field=models.CharField(blank=True, choices=[('01', '활성화'), ('02', '비활성화')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_ot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_rm_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_tot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='motor_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='og_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_close_sequence',
            field=models.CharField(blank=True, choices=[('01', '1번 그룹부터'), ('02', '2번 그룹부터')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_delay_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_high_temp_mode',
            field=models.CharField(blank=True, choices=[('01', '활성화'), ('02', '비활성화')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_high_temp_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_mode',
            field=models.CharField(blank=True, choices=[('01', '자동'), ('02', '수동')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_open_sequence',
            field=models.CharField(blank=True, choices=[('01', '1번 그룹부터'), ('02', '2번 그룹부터')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_rain_mode',
            field=models.CharField(blank=True, choices=[('01', '활성화'), ('02', '비활성화')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlopenoption',
            name='om_rain_option',
            field=models.IntegerField(default=0),
        ),
    ]
