# Generated by Django 2.0.7 on 2019-01-08 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorinfoorvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorinfoorvalue',
            name='test_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='co2_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='co2_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='co2_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='cultrue_medium_temp_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='culture_medium_temp_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='culture_medium_temp_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='humd_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='humd_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='humd_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ec_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ec_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ec_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ph_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ph_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ph_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_ec_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_ec_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_ec_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_humd_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_humd_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_humd_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_temp_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_temp_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_temp_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='temp_id1',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='temp_id2',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='temp_id3',
            field=models.CharField(default='0000', max_length=6),
        ),
    ]
