# Generated by Django 2.0.7 on 2019-01-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0003_auto_20190107_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlopengroup',
            name='og_name',
            field=models.IntegerField(default=0),
        ),
    ]
