# Generated by Django 2.0.7 on 2019-01-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0005_auto_20190109_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='co2_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='culture_medium_temp_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='humd_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ec_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='nutrient_solution_ph_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_ec_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_humd_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='soil_temp_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='temp_num',
            field=models.IntegerField(default=0),
        ),
    ]
