# Generated by Django 2.0.7 on 2019-01-09 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0007_auto_20190109_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='test_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='wind_dir_value',
            field=models.CharField(max_length=50),
        ),
    ]
