# Generated by Django 2.0.7 on 2019-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0008_auto_20190109_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='display_data',
            field=models.BooleanField(default=False),
        ),
    ]
