# Generated by Django 2.0.7 on 2019-01-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0009_weatherinfo_display_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='display_data',
        ),
        migrations.AddField(
            model_name='sensorinfoorvalue',
            name='display_data',
            field=models.BooleanField(default=False),
        ),
    ]
