# Generated by Django 2.0.7 on 2019-01-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0010_auto_20190109_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date1', models.DateTimeField(auto_now_add=True)),
                ('test_date2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
