# Generated by Django 2.0.7 on 2019-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0011_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorinfoorvalue',
            old_name='cultrue_medium_temp_id3',
            new_name='culture_medium_temp_id3',
        ),
        migrations.AlterField(
            model_name='sensorinfoorvalue',
            name='test_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
